M48
; DRILL file {KiCad 8.0.7} date 2024-12-30T17:39:48+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-30T17:39:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X4.4169Y-8.6549
X4.4169Y-8.8825
T2
X4.5098Y-3.6909
X4.5098Y-5.2657
M30
